version: "2"
services:

  mw-ui:
    image: openlmis/dev-ui:9.0.6
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - offline-ui
      - mw-dhis2-integration-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - offline-ui
      - mw-dhis2-integration-ui

  auth-ui:
    image: openlmis/auth-ui:6.2.12
    volumes:
      - '/openlmis-auth-ui'

  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.1.4
    volumes:
      - '/openlmis-fulfillment-ui'

  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.12
    volumes:
      - '/openlmis-referencedata-ui'

  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.1.6
    volumes:
      - '/openlmis-stockmanagement-ui'

  cce-ui:
    image: openlmis/cce-ui:1.1.5
    volumes:
     - '/openlmis-cce-ui'

  report-ui:
    image: openlmis/report-ui:5.2.11
    volumes:
      - '/openlmis-report-ui'

  requisition-ui:
    image: openlmis/requisition-ui:7.0.12
    volumes:
      - '/openlmis-requisition-ui'

  ui-components:
    image: openlmis/ui-components:7.2.11
    volumes:
      - '/openlmis-ui-components'

  ui-layout:
    image: openlmis/ui-layout:5.2.5
    volumes:
      - '/openlmis-ui-layout'

  offline-ui:
    image: openlmis/offline-ui:1.0.5
    volumes:
      - '/openlmis-offline-ui'

  mw-dhis2-integration-ui:
    image: openlmismw/dhis2-integration-ui:1.0.2
    volumes:
      - '/mw-dhis2-integration-ui'

  image:
    build: .
    image: openlmismw/ui-with-production-settings
